<?php	return array (
    'SITE_INFO' => array (
        'name' => '科技有限公司',
        'keyword' => '我的关键词',
        'description' => '这里写描述',
        'LANG_SWITCH_ON' => 1,
        'version' => 'Conist 企业站系统Bate2.0',
        'url' => 'http://jyjz.com/',
        ),
    'LISTNUM' => array (
        'DEFAULT_THEME' => 'default',
        'prolist' => 12,
        'newslist' => 12,
        'noIndColor' => '#4f6128',
        ),
    'TOKEN' => array (
        'false_static' => 1,
        'mess_on' => 1,
        'admin_marked' => 'http://www.uc22.net',
        'admin_timeout' => 3600,
        'member_marked' => 'http://www.uc22.net',
        'member_timeout' => 3600,
        ),
    'WEB_ROOT' => 'http://jyjz.com/',
    'AUTH_CODE' => 'EGYumd',
    'ADMIN_AUTH_KEY' => 'bigqig@126.com',
    'DB_HOST' => 'localhost',
    'DB_NAME' => 'intelligencemine',
    'DB_USER' => 'root',
    'DB_PWD' => 'root',
    'DB_PORT' => '3306',
    'DB_PREFIX' => 'pa_',
    'webPath' => '/',
    );
?>